services:
  db:
    image: mysql:8.0
    container_name: messaging_app_mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'my-app-db'
      MYSQL_USER: 'root'
      #MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: ''    
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "",
          "-e",
          "SELECT 1",
        ]
      timeout: 20s
      retries: 10
    volumes:
      - db-datavolume:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging_app_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      SECRET_KEY: "some_key"
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-datavolume:
